In [5]:
import numpy as np
import pandas as pd

from sklearn.decomposition import TruncatedSVD

In [6]:
df_recsys = pd.read_csv('./data/sb_restaurants_clean.csv', index_col=0) 
df_recsys.head()

,user_id,business_id,stars,name
0,59MxRhNVhU9MYndMkz0wtw,gebiRewfieSdtt17PTW6Zg,3,Hibachi Steak House & Sushi Bar
1,lUYboGI6aFbZ0dX27pijpA,gebiRewfieSdtt17PTW6Zg,1,Hibachi Steak House & Sushi Bar
2,SrfDRvGKI8FQq9LCr0dQuQ,gebiRewfieSdtt17PTW6Zg,3,Hibachi Steak House & Sushi Bar
3,SfMf7DEX7xT82OCcbZFsgQ,gebiRewfieSdtt17PTW6Zg,5,Hibachi Steak House & Sushi Bar
4,aH3AH7V9g60w4pt3LpJ1_Q,gebiRewfieSdtt17PTW6Zg,4,Hibachi Steak House & Sushi Bar

In [4]:
df_recsys.shape

(3031, 4)

In [9]:
idx = (df_recsys['user_id']== 'SrfDRvGKI8FQq9LCr0dQuQ')

print('Total de restaurantes calificados por el usuario: ',idx.sum())
df_recsys[idx]

Total de restaurantes calificados por el usuario:  4

,user_id,business_id,stars,name
2,SrfDRvGKI8FQq9LCr0dQuQ,gebiRewfieSdtt17PTW6Zg,3,Hibachi Steak House & Sushi Bar
1234,SrfDRvGKI8FQq9LCr0dQuQ,kZtl_NJjUnlIQgzFrBhXyQ,4,Ichiban
2479,SrfDRvGKI8FQq9LCr0dQuQ,HQ-C47_Xi5it1KzwEc0u0A,4,Barbarians
2716,SrfDRvGKI8FQq9LCr0dQuQ,vLT1KtrA9bWvjFOg-0xVIg,4,Pieology Pizzeria

In [10]:
UtlMtrx = df_recsys.pivot_table(values='stars', index='user_id', 
                                columns='name', fill_value=0
                                )
UtlMtrx.head()

name,805 Kabob,Backyard Bowls,Barbarians,Beans BBQ and Catering,Bevmo,Bluewater Grill - Santa Barbara,Borrello's Pizza & Pastaria,Breakfast Culture Club,Brummis - the German Taste,Cafe Buenos Aires,...,TonyRay's Restaurant & Cantina,Tre Lune,Tsukemono,Tuttini,University Club of Santa Barbara,Wahoo's Fish Tacos,Wok On the Wild Side,Yoichi's,Yoshinoya,Zen Yai Thai Cuisine
user_id,,,,,,,,,,,,,,,,,,,,,
--KMTwCrhKKUmr7riuS4WQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
--hyXh5WffOsWvD6Zg-xsQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-0IiMAZI2SsQ7VmyzJjokQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-1WbN1Qd-opw8u3uEqs2Kg,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
-62S7530a_htLZPWWEgh0Q,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
print('Total de elementos de la matriz de utilidad: %d' % (UtlMtrx.size))
print('Total de elementos diferentes de cero: %d' % (np.count_nonzero(UtlMtrx)))
print('Porcentaje de elementos diferentes de cero: %.1f%%' % (100 * np.count_nonzero(UtlMtrx) / UtlMtrx.size))

Total de elementos de la matriz de utilidad: 265644
Total de elementos diferentes de cero: 3011
Porcentaje de elementos diferentes de cero: 1.1%

In [12]:
X = UtlMtrx.T

print(X.shape)
X.head()

(94, 2826)

user_id,--KMTwCrhKKUmr7riuS4WQ,--hyXh5WffOsWvD6Zg-xsQ,-0IiMAZI2SsQ7VmyzJjokQ,-1WbN1Qd-opw8u3uEqs2Kg,-62S7530a_htLZPWWEgh0Q,-6Zpg6_0ZR-f3Lo_hAvBXw,-7Eh_8y1ihj3nNtdIetiRA,-8SmhfAtbA56qSWdP3xCYw,-9wZ5ndiE6jEVet0j7PKXw,-AvKXy-4egzfXZA5jLCW9A,...,zp7QEtdpzgIIloQIyx6fGw,zpX-98VD2-GpGnhiQwCySA,zqKVamdXmqdQZWVm5mMxpA,zqQyPjRJRoh4X2RBBkbd0w,zqVvsgvWzpRnVD08QwhSvw,zqWAjgMm8mK8h1dUiCfbcA,zrrt2HRQdiM9IJGyeJoYag,zsPcZb2K9YJGOPg2RE0eTg,ztmmfBKOCfMj_8tsaHj18A,zyApbnUwHafJUvDtiO3Gcw
name,,,,,,,,,,,,,,,,,,,,,
805 Kabob,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Backyard Bowls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Barbarians,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Beans BBQ and Catering,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bevmo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
SVD = TruncatedSVD(n_components=93, random_state=42)  
SVD.fit(X)

num_sv = 7

print('Cantidad de información simplificada con los primeros %d vectores singulares:' % num_sv)
print('%.1f%%' %  (100 * (1- (SVD.singular_values_[0:num_sv]).sum() / (SVD.singular_values_).sum())))

Cantidad de información simplificada con los primeros 7 vectores singulares:
80.2%

In [22]:
num_sv = 7

SVD = TruncatedSVD(n_components=num_sv, random_state=42)

resultant_matrix = SVD.fit_transform(X)
resultant_matrix.shape

(94, 7)

In [23]:
corrMtx = np.corrcoef(resultant_matrix)
 
corrMtx[0:5,0:5]

array([[ 1.        , -0.86734848, -0.87002934, -0.26859208, -0.18417184],
       [-0.86734848,  1.        ,  0.99985994,  0.40427906, -0.01907276],
       [-0.87002934,  0.99985994,  1.        ,  0.40639032, -0.02590645],
       [-0.26859208,  0.40427906,  0.40639032,  1.        ,  0.02406848],
       [-0.18417184, -0.01907276, -0.02590645,  0.02406848,  1.        ]])

In [32]:
liked = 'Barbarians'

names = UtlMtrx.columns 
names_list = list(names)
id_liked = names_list.index(liked)

id_liked

2

In [33]:
corr_recom = corrMtx[id_liked]
print(corr_recom.shape)
corr_recom[0:10]

(94,)

array([-0.87002934,  0.99985994,  1.        ,  0.40639032, -0.02590645,
        0.51640192, -0.66319197,  0.3294516 ,  0.36669669, -0.20166108])

In [34]:
corr_recom[id_liked]

1.0

In [35]:
print('Recomendaciones: ')

list(names[(corr_recom > 0.80) & (corr_recom < 0.99)])

Recomendaciones:

['Epiphany Restaurant', 'Hob Nob']

In [37]:
ids = (corr_recom > .80) & (corr_recom < 0.99)
tmp = list()

for i in range(len(names[ids])):
    tmp.append((corr_recom[ids][i], names[ids][i]))

sorted(tmp, key=lambda x:x[0], reverse=True)

[(0.9671937622521009, 'Hob Nob'), (0.9664472028240986, 'Epiphany Restaurant')]